require('lua/options')
require('lua/plugins')
require('lua/plugins/lsp_installer') -- Needs To be sourced Prior to lsp_config
require('lua/plugins/lsp_config')
require('lua/plugins/cmp')
require('lua/plugins/luasnip')
require('lua/plugins/treesitter')
require('lua/plugins/autopairs')
require('lua/plugins/gitsigns')
require('lua/plugins/themer')
require('lua/plugins/wilder')
require('lua/plugins/rainbow')
